bp_debouce: bpDebounce_callback Class Reference
bpDebounce_callback Class Reference
class pour la gestion des fonction callback atrribuer a l'état du bouton
#include <bp_debouce.h>
Public Member Functions
bpDebounce_callback (_BP_callbackFunc *func)
constructor instancier par la class bpDebounceHandle
void activate (boolean &ret)
GETTER: etat de kactivation de l'appele du callback.
void toglle ()
activation/desactivation de l'appel de la fonction callback
void func ()
appel de la fonction callback
void func_change (_BP_callbackFunc *func)
changement du ptr de la fonction callback
Private Attributes
mBPDc _mod = mBPDc_none
type de pression
_BP_callbackFunc _func = NULL
callback
boolean _activate = true
activation/desactivation du callback
Detailed Description
class pour la gestion des fonction callback atrribuer a l'état du bouton
See also
https://github.com/AdriLighting/
Author
Adrien Grellard
Date
2021
Definition at line 139 of file bp_debouce.h.
Constructor & Destructor Documentation
bpDebounce_callback()
bpDebounce_callback::bpDebounce_callback (_BP_callbackFunc * func)
constructor instancier par la class bpDebounceHandle
See also
https://github.com/AdriLighting/
Author
Adrien Grellard
Parameters
ptr ver la fonction callback
Definition at line 150 of file bp_debouce.cpp.
{
    _func = *func;
}
References _func, and func().
Member Function Documentation
activate()
void bpDebounce_callback::activate (boolean & ret)
GETTER: etat de kactivation de l'appele du callback.
See also
https://github.com/AdriLighting/
Author
Adrien Grellard
Parameters
ret ret = valeur par reference
Definition at line 200 of file bp_debouce.cpp.
{
    ret = _activate;
}
References _activate.
Referenced by bpDebounceHandle::callback_isActivate().
func()
void bpDebounce_callback::func ()
appel de la fonction callback
See also
https://github.com/AdriLighting/
Author
Adrien Grellard
Definition at line 174 of file bp_debouce.cpp.
{
    if (!_activate) return;
    _func();
}
References _activate, and _func.
Referenced by bpDebounce_callback(), func_change(), and bpDebounceHandle::loop().
func_change()
void bpDebounce_callback::func_change (_BP_callbackFunc * func)
changement du ptr de la fonction callback
See also
https://github.com/AdriLighting/
Author
Adrien Grellard
Parameters
ptr ver la fonction callback
Definition at line 163 of file bp_debouce.cpp.
{
    _func = *func;
}
References _func, and func().
Referenced by bpDebounceHandle::callback().
toglle()
void bpDebounce_callback::toglle ()
activation/desactivation de l'appel de la fonction callback
See also
https://github.com/AdriLighting/
Author
Adrien Grellard
Definition at line 186 of file bp_debouce.cpp.
{
    _activate = !_activate;
}
References _activate.
Referenced by bpDebounceHandle::callback_toglle().
Member Data Documentation
_activate
boolean bpDebounce_callback::_activate = true private
activation/desactivation du callback
Definition at line 143 of file bp_debouce.h.
Referenced by activate(), func(), and toglle().
_func
_BP_callbackFunc bpDebounce_callback::_func = NULL private
callback
Definition at line 142 of file bp_debouce.h.
Referenced by bpDebounce_callback(), func(), and func_change().
_mod
mBPDc bpDebounce_callback::_mod = mBPDc_none private
type de pression
Definition at line 141 of file bp_debouce.h.
The documentation for this class was generated from the following files:
bp_debouce.h
bp_debouce.cpp