bp_debouce: bpDebounce_management Class Reference
bpDebounce_management Class Reference
class pour la gestion general des toutes les classes
#include <bp_debouce.h>
Public Member Functions
bpDebounce_management ()
Constructs a new instance (statique instance)
void addBp (int pin, boolean pullup, uint8_t mode, int &result)
Adds a bp.
void loop ()
backgroud
void callback (int bp, mBPDc mod, _BP_callbackFunc func)
creation des callback
void callback_toglle (int bp, mBPDc mod)
void print (int bp)
void print ()
Private Attributes
int _pos = 0
Detailed Description
class pour la gestion general des toutes les classes
See also
https://github.com/AdriLighting/
Author
Adrien Grellard
Date
2021
Definition at line 217 of file bp_debouce.h.
Constructor & Destructor Documentation
bpDebounce_management()
bpDebounce_management::bpDebounce_management ()
Constructs a new instance (statique instance)
See also
https://github.com/AdriLighting/
Author
Adrien Grellard
Definition at line 484 of file bp_debouce.cpp.
{
     #ifdef DEBUG
     #endif
 }
Member Function Documentation
addBp()
void bpDebounce_management::addBp (int pin, boolean pullup, uint8_t mode, int & result)
Adds a bp.
See also
https://github.com/AdriLighting/
Author
Adrien Grellard
Parameters
[in] pin The pin
[in] pullup The pullup
[in] mode The mode
result valeure de la postion de larray des instance
Definition at line 502 of file bp_debouce.cpp.
{
     bpDebounceArray[_pos]       = new bpDebounce(pin, pullup, mode);
     bpDebounceHandleArray[_pos] = new bpDebounceHandle(bpDebounceArray[_pos]);
     result = _pos;
     _pos++;
 }
References _pos, bpDebounceArray, and bpDebounceHandleArray.
callback()
void bpDebounce_management::callback (int bp, mBPDc mod, _BP_callbackFunc func)
creation des callback
See also
https://github.com/AdriLighting/
Author
Adrien Grellard
Parameters
[in] bp postion de larray des instance
[in] mod type de callback
[in] func fonction referente
Definition at line 534 of file bp_debouce.cpp.
{
     bpDebounceHandleArray[bp]->callback(mod, func);
 }
References bpDebounceHandleArray, and bpDebounceHandle::callback().
callback_toglle()
void bpDebounce_management::callback_toglle (int bp, mBPDc mod)
Definition at line 538 of file bp_debouce.cpp.
{
     bpDebounceHandleArray[bp]->callback_toglle(mod);
 }
References bpDebounceHandleArray, and bpDebounceHandle::callback_toglle().
loop()
void bpDebounce_management::loop ()
backgroud
See also
https://github.com/AdriLighting/
Author
Adrien Grellard
Definition at line 516 of file bp_debouce.cpp.
{
     for (int i = 0; i < _pos; ++i)
     {
         bpDebounceHandleArray[i]->loop();
     }
 }
References _pos, bpDebounceHandleArray, and bpDebounceHandle::loop().
print() [1/2]
void bpDebounce_management::print ()
Definition at line 609 of file bp_debouce.cpp.
{
     for (int i = 0; i < _pos; ++i) {print(i);}
 }
References _pos.
print() [2/2]
void bpDebounce_management::print (int bp)
Definition at line 558 of file bp_debouce.cpp.
{
 #ifdef DEBUG
     uint8_t tempStrArraySize    = 10;
     String * tempStrArray       = new String[tempStrArraySize];
     String paddingStr;
     int         pin;
     boolean     statu;
     boolean     pullup;
     uint8_t     input;
     boolean     callbackRegister[5];
     boolean     callbackActivate[5];
     bpDebounceHandleArray[bp]->_bpDebounce->pinGet(pin);
     bpDebounceHandleArray[bp]->_bpDebounce->pullupGet(pullup);
     bpDebounceHandleArray[bp]->_bpDebounce->inputGet(input);
     bpDebounceHandleArray[bp]->_bpDebounce->statuGet(statu);
     for (int i = mBPDc_click_1; i < mBPDc_none; ++i) {
         bpDebounceHandleArray[bp]->callback_isRegister(mBPDcArray[i], callbackRegister[i]);
         if (callbackRegister[i]) {
             bpDebounceHandleArray[bp]->callback_isActivate(mBPDcArray[i], callbackActivate[i]);
         }
     }
     tempStrArray[0] = "BP : " + String(bp) + "\n";
     padding(paddingStr, fsget(p_bpd_pin),       String(pin),    20);
     tempStrArray[1] =  paddingStr;
     padding(paddingStr, fsget(p_bpd_pullup),    String(pullup), 20);
     tempStrArray[2] =  paddingStr;
     padding(paddingStr, fsget(p_bpd_input),     String(input),  20);
     tempStrArray[3] =  paddingStr;
     padding(paddingStr, fsget(p_bpd_statu),     String(statu),  20);
     tempStrArray[4] =  paddingStr;
     int cnt = 5;
     for (int i = mBPDc_click_1; i < mBPDc_none; ++i) {
         if (callbackRegister[i]) {
             padding(paddingStr, mBPDc_toString(mBPDcArray[i]) , String(callbackActivate[i]), 20);
             tempStrArray[cnt] =  paddingStr;
         }  else {
             padding(paddingStr, mBPDc_toString(mBPDcArray[i]) , "unregistered", 20);
             tempStrArray[cnt] = paddingStr;
         }
         cnt++;
     }
     for (int i = 0; i < tempStrArraySize; ++i){
         Serial.println(tempStrArray[i]);
     }
 #endif
 }
References bpDebounceHandle::_bpDebounce, bpDebounceHandleArray, bpDebounceHandle::callback_isActivate(), bpDebounceHandle::callback_isRegister(), bpDebounce::inputGet(), mBPDc_click_1, mBPDc_none, mBPDcArray, bpDebounce::pinGet(), bpDebounce::pullupGet(), and bpDebounce::statuGet().
Member Data Documentation
_pos
int bpDebounce_management::_pos = 0 private
Definition at line 219 of file bp_debouce.h.
Referenced by addBp(), loop(), and print().
The documentation for this class was generated from the following files:
bp_debouce.h
bp_debouce.cpp